using System;
using System.IO;
using FS27.Core;

// Writes sample previews of characters generated by the Creator Engine (procedural mannequin: not final art, not rigged, not animated).
internal static class Program
{
    private static int Main(string[] args)
    {
        string dir = args.Length > 0 ? args[0] : "Docs/previews";
        Directory.CreateDirectory(dir);
        CreatorPipeline pipeline = CreatorPipeline.CreateDefault();
        string[] names = { "winger", "goalkeeper", "striker" };
        string[] prompts =
        {
            "Crea un extremo rápido, alto, con pelo negro rizado y barba corta",
            "Crea un portero muy alto, ágil, con buenos reflejos, estiradas espectaculares y buen juego con los pies, seguro y tranquilo",
            "Crea un delantero pequeño, delgado, calvo, con ojos azules y muy rápido"
        };
        for (int i = 0; i < names.Length; i++)
        {
            CreatorResult r = pipeline.Run(new CreatorRequest { Text = prompts[i], Seed = 7, WantPreviewPng = true, WantGlb = true, CharacterId = names[i] });
            File.WriteAllBytes(Path.Combine(dir, names[i] + ".png"), r.Preview.PngBytes);
            File.WriteAllBytes(Path.Combine(dir, names[i] + ".glb"), r.Preview.GlbBytes);
            File.WriteAllText(Path.Combine(dir, names[i] + ".debug.txt"), r.DebugReport);
            File.WriteAllText(Path.Combine(dir, names[i] + ".runtime.json"), r.RuntimeData.Json);
            Console.WriteLine(names[i] + ": success=" + r.Success + ", height " + r.GenerationPlan.Assembly.Proportions.HeightMeters.ToString("0.00") + " m, runtime record " + r.RuntimeData.Bytes + " bytes");
        }
        return 0;
    }
}
